package com.abbyberkers.apphome.communication.textformatters

/**
 * @param hours Map from an hour to the translation of that number.
 * @param minutes Map from a value of minutes to the translation.
 * @param connectors Map from minutes to the expression used to connect the minutes to the hours in a language.
 * @param nextHourThreshold The threshold for when to use the next hour in spoken language.
 * @param maxMinutes The maximum number of minutes used in spoken language. With 30 being the only exception.
 */
enum class Language(val hours: Map<Int, String>,
                    val minutes: Map<Int, String>,
                    val connectors: Map<Int, String>,
                    val nextHourThreshold: Int,
                    val maxMinutes: Int) {
    DUTCH(hours = mapOf(1 to "een",
                2 to "twee",
                3 to "drie",
                4 to "vier",
                5 to "vijf",
                6 to "zes",
                7 to "zeven",
                8 to "acht",
                9 to "negen",
                10 to "tien",
                11 to "elf",
                0 to "twaalf"),
            minutes = mapOf(0 to "uur",
                5 to "vijf",
                10 to "tien",
                15 to "kwart",
                30 to ""),
            connectors = mapOf(
                5 to "over",
                10 to "over",
                15 to "over",
                20 to "voor half",
                25 to "voor half",
                30 to "half",
                35 to "over half",
                40 to "over half",
                45 to "voor",
                50 to "voor",
                55 to "voor"),
            nextHourThreshold = 18,
            maxMinutes = 15
    ),
    ENGLISH(hours = mapOf(1 to "one",
                2 to "two",
                3 to "three",
                4 to "four",
                5 to "five",
                6 to "six",
                7 to "seven",
                8 to "eight",
                9 to "nine",
                10 to "ten",
                11 to "eleven",
                0 to "twelve"),
            minutes = mapOf(0 to "o'clock",
                5 to "five",
                10 to "ten",
                15 to "quarter",
                20 to "twenty",
                25 to "twenty-five",
                30 to "thirty"),
            connectors = mapOf(0 to "",
                5 to "past",
                10 to "past",
                15 to "past",
                20 to "past",
                25 to "past",
                30 to " past",
                35 to "to",
                40 to "to",
                45 to "to",
                50 to "to",
                55 to "to"),
            nextHourThreshold = 33,
            maxMinutes = 30
    ) }